### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by MrLotU** [apple/swift-metrics-extras#12]
I just realized this when trying to use this in one of my projects, but this package never got it's first release published. Could we get a 1.0 released anytime soon? 😄

**Comment by philippzagar** [comment]
@ktoso Are there any updates from @fabianfett regarding #11? After merging, the 1.0 or 0.X tag should be good to go

**Comment by ktoso** [comment]
Merged and tagged 0.1.0!

Sorry it took us a while but at least still before x-mas break :)
